model_params:
  name: 'Decoder'
  in_channels: 2
  label_dim: 10

data_params:
  # data_path: "Data/"
  data_cfg: "a1"
  augments: True
  train_batch_size: 1024
  val_batch_size:  1024
  patch_size: 64
  num_workers: 12


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  # gpus: [1]
  max_epochs: 50

logging_params:
  # save_dir: "/storage/liav/storage/metalens/vae_logs/"
  save_dir: "/mnt/storage/datasets/liav/vae_logs/"
  name: "decoder-a1"
